test: testing lighhouse ci

diff --git a/.github/workflows/lighhouse.yml b/.github/workflows/lighhouse.yml
--- a/.github/workflows/lighhouse.yml
+++ b/.github/workflows/lighhouse.yml
@@ -35,7 +35,7 @@ jobs:
       #     LHCI_GITHUB_APP_TOKEN: $
           
       - name: Run Lighthouse CI
-        run: npx @lhci/cli autorun --config=./lighthouserc.js || echo "LHCI failed!"
+        run: npx @lhci/cli autorun --config=./lighthouserc.cjs || echo "LHCI failed!"
 
       - name: Upload Lighthouse reports
         uses: actions/upload-artifact@v4
